apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
data:
  config.inc.php: |    
    <?php
    /**
     * phpMyAdmin sample configuration, you can use it as base for
     * manual configuration. For easier setup you can use setup/
     *
     * All directives are explained in documentation in the doc/ folder
     * or at <https://docs.phpmyadmin.net/>.
     *
    * @package PhpMyAdmin
     */
    
    /**
     * This is needed for cookie based authentication to encrypt password in
     * cookie. Needs to be 32 chars long.
     */
    $cfg['blowfish_secret'] = '01234567890123456789012345678912'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */
    
    /**
     * Servers configuration
     */
    $i = 0;
    
    /**
     * First server
     */
    $i++;
    
    /* Authentication type */
    $cfg['Servers'][$i]['auth_type'] = 'cookie';
    
    /* Server parameters */
    $cfg['Servers'][$i]['host'] = 'mysql';
    $cfg['Servers'][$i]['port'] = '3306';
    $cfg['Servers'][$i]['user'] = 'admin';
    $cfg['Servers'][$i]['password'] = 'tkdgur123';
    $cfg['Servers'][$i]['compress'] = 'false';
    $cfg['Servers'][$i]['AllowNoPassword'] = 'false';
    
    /**
     * Directories for saving/loading files from server
     */
    $cfg['UploadDir'] = '';
    $cfg['SaveDir'] = '';