apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
        tier: backend
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      containers:
      - name: nginx
        image: ft_nginx:1.0
        imagePullPolicy: Never #이미지가 로컬에 있다고 가정합니다.
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts: #nginx, ssl 설정을 볼륨 마운트를 통해 전달!
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
        livenessProbe: # 만약 kubectl exec deploy/nginx -- pkill sshd로 sshd 프로세스를 죽이면 컨테이너 재시작
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          tcpSocket:
            port: 22