apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports: #포트가 두개 일때 포트 이름을 명시해줘야함. #target port가 기본적으로 port와 같게 설정되어있다.
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 22
    name: ssh
  selector:
    app: nginx
    tier: backend