apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb
  labels:
    app: influxdb
data:
  influxdb.conf: |
    reporting-disabled = false # 24시간 주기로 influxdb.com에 데이터 보낼지 여부
    bind-address = "127.0.0.1:8088" # RPC(remote procedure controler) 네트워크 상의 다른 컴퓨터와 통신할 때 사용하는 프로토콜. 다른 네트워크에 있는 telegraf, grafana 등의 프로그램과 통신을 사용해야 하므로 열어준다.
    ###
    ### [meta]
    ###
    ### Controls the parameters for the Raft consensus group that stores metadata
    ### about the InfluxDB cluster.
    ###
    [meta]
      dir = "/var/lib/influxdb/meta" # meta db가 담길 위치
      retention-autocreate = true # 잘 모르겠다.
      logging-enabled = true # 로그 기록
    [data]
      dir = "/var/lib/influxdb/data" # TSM file이 저장되는 곳- TIME STRUCTURED MERGE TREE
      wal-dir = "/var/lib/influxdb/wal" # WAL file이 저장되는 곳
      wal-fsync-delay = "0s" # 0s는 WAL을 계속 기록. 컴퓨터가 안좋으면 0 이상의 값을 사용
      index-version = "inmem" # 잘 모르겠다. 디폴트값 사용
      trace-logging-enabled = false # 디버깅 할 때 사용하면 될 듯.
      query-log-enabled = true # true로 하자. 실행할 때 오류나면 로그 보여줌
      cache-max-memory-size = "1g"
      cache-snapshot-memory-size = "25m"
      compact-full-write-cold-duration = "4h"
      cache-snapshot-write-cold-duration = "10m"
      max-concurrent-compactions = 0
      tsm-use-madv-willneed = false
      # 아래 두 개는 inmem 에 대한 옵션
      max-series-per-database = 1000000
      max-values-per-tag = 100000
      max-index-log-file-size = "1m"
 
    ###
    ### [coordinator]
    ###
    ### Controls the clustering service configuration.
    ###
    [coordinator] # default
      write-timeout = "10s" # 10초 동안 응답없으면 timeout error
      max-concurrent-queries = 0 # 0이면 동시에 동작하는 쿼리에 제한이 없다
      query-timeout = "0s"
      log-queries-after = "0s"
      max-select-point = 0
      max-select-series = 0
      max-select-buckets = 0

    [retention] # 오래된 데이터를 보존하기 위한 설정들 디폴트로 하면 된다.
      enabled = true #default
      check-interval = "30m0s"

    [shard-precreation] # default
      enabled = true
      check-interval = "10m0s"
      advance-period = "30m0s"

    [monitor] #default
      store-enabled = true
      store-database = "_internal"
      store-interval = "10s"

    [subscriber] # default
      enabled = true
      http-timeout = "30s"
      insecure-skip-verify = false
      ca-certs = ""
      write-concurrency = 40
      write-buffer-size = 1000

    [http] # default
      enabled = true
      bind-address = ":8086"
      auth-enabled = false
      log-enabled = true
      access-log-path = ""
      realm = "InfluxDB"
      suppress-write-log = false
      write-tracing = false
      pprof-enabled = true
      debug-pprof-enabled = false
      https-enabled = false
      max-row-limit = 0
      max-connection-limit = 0
      shared-secret = ""
      unix-socket-enabled = false
      unix-socket-permissions = "0777"
      bind-socket = "/var/run/influxdb.sock"
      max-body-size = 25000000
      max-concurrent-write-limit = 0
      max-enqueued-write-limit = 0
      enqueued-write-timeout = 30000000000

    [logging] # default
      format = "auto"
      level = "info"
      suppress-logo = false

    [ifql]
      enabled = false
      log-enabled = true
      bind-address = ":8082"

    [[graphite]] # default
      enabled = false
      database = "telegraf" # 중요!
      retention-policy = ""
      bind-address = ":2003"
      protocol = "tcp"
      consistency-level = "one"
      batch-size = 5000
      batch-pending = 10
      batch-timeout = "1s"
      udp-read-buffer = 0
      separator = "."
      templates = [ #https://gatling.io/docs/current/realtime_monitoring 참고
                "gatling.*.*.*.* measurement.simulation.request.status.field",
                "gatling.*.users.*.* measurement.simulation.measurement.request.field"
      ]
      #      templates = [
      #        "gatling.*.*.*.*.*.* measurement.test.injector.simulation.request.status.field",
      #        "gatling.*.*.*.users.*.* measurement.test.injector.simulation.measurement.request.field"
      #      ]

    [[collectd]]
      enabled = false
      bind-address = ":25826"
      database = "collectd"
      retention-policy = ""
      batch-size = 5000
      batch-pending = 10
      batch-timeout = "10s"
      read-buffer = 0
      typesdb = "/usr/share/collectd/types.db" #  폴더만 지정해준게 아닌 db 파일을 명확히 지정
      security-level = "none"
      auth-file = "/etc/collectd/auth_file"
      parse-multivalue-plugin = "split"

    [[opentsdb]]
      enabled = false
      bind-address = ":4242"
      database = "opentsdb"
      retention-policy = ""
      consistency-level = "one"
      tls-enabled = false
      certificate = "/etc/ssl/influxdb.pem"
      batch-size = 1000
      batch-pending = 5
      batch-timeout = "1s"
      log-point-errors = true

    [[udp]]
      enabled = false
      bind-address = ":8089"
      database = "udp"
      retention-policy = ""
      batch-size = 5000
      batch-pending = 10
      read-buffer = 0
      batch-timeout = "1s"
      precision = ""

    [continuous_queries]
      log-enabled = true
      enabled = true
      query-stats-enabled = false
      run-interval = "1s"

    [tls]
      min-version = ""
      max-version = ""