apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - port: 5000
      name: phpmyadmin
      targetPort: 5000