apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_USER: iwoo
  INFLUXDB_USER_PASSWORD: iwoo123