apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: ft_telegraf
          imagePullPolicy: Never
          volumeMounts:
            - name: telegraf-config
              subPath: telegraf.conf
              mountPath: /etc/telegraf/telegraf.conf
              readOnly: true
            - name: docker-unix-socket
              mountPath: /var/run/docker.sock
          envFrom: # secret로 환경 변수 가져온다. 환경 변수에 db 정보 들어있음.
            - secretRef:
                name: telegraf
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf
        - name: docker-unix-socket # 이 소켓을 통해서 데이터를 가져온다.
          hostPath:
            path: /var/run/docker.sock
            type: Socket