apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 20000
        - containerPort: 20001
        env:
        - name: USERNAME
          value: iwoo
        - name: PASSWORD
          value: iwoo123
        volumeMounts:
        - name: ftps-config
          subPath: vsftpd.conf
          mountPath: /etc/vsftpd/vsftpd.conf
      volumes:
        - name: ftps-config
          configMap:
            name: ftps-config