apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftp-data
    port: 20
    targetPort: 20
  - name: ftp-connection
    port: 21
    targetPort: 21
  - name: pftp-data-0
    port: 20000
    targetPort: 20000
  - name: pftp-data-1
    port: 20001
    targetPort: 20001